services:
  # 1. Redis: 用于长连接路由、PubSub 广播、离线消息 ZSet
  redis:
    image: redis:7-alpine
    container_name: linkgo-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 123456

  # 2. MySQL: 用于消息持久化、历史记录拉取、用户/群组元数据存储
  mysql:
    image: mysql:8.0
    container_name: linkgo-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=linkgo_im
    volumes:
      # 挂载初始化脚本，确保一键部署时自动创建 messages 表
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # 3. Logic: 业务逻辑层（处理 MySQL 入库、群聊分发算法）
  logic:
    build: .
    container_name: linkgo-logic
    command: ./logic
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - REDIS_ADDR=redis:6379
      - DB_DSN=root:root@tcp(mysql:3306)/linkgo_im?charset=utf8mb4&parseTime=True&loc=Local

  # 4. Gateway A: 网关入口（处理 RESTful API 与 WebSocket）
  gateway-a:
    build: .
    container_name: linkgo-gateway-a
    command: ./gateway
    ports:
      - "8090:8090"
    depends_on:
      - logic
      - redis
    environment:
      - GATEWAY_PORT=8090
      - LOGIC_ADDR=logic:9001
      - REDIS_ADDR=redis:6379

  # 5. Gateway B: 模拟分布式多节点（验证跨节点广播）
  gateway-b:
    build: .
    container_name: linkgo-gateway-b
    command: ./gateway
    ports:
      - "8091:8090" # 映射外部 8091 到容器内部 8090
    depends_on:
      - logic
      - redis
    environment:
      - GATEWAY_PORT=8090
      - LOGIC_ADDR=logic:9001
      - REDIS_ADDR=redis:6379

  # 6. Gateway C: 第三个网关节点（增加并发承载）
  gateway-c:
    build: .
    container_name: linkgo-gateway-c
    command: ./gateway
    ports:
      - "8092:8090"
    depends_on:
      - logic
      - redis
    environment:
      - GATEWAY_PORT=8090
      - LOGIC_ADDR=logic:9001
      - REDIS_ADDR=redis:6379