// Code generated by goctl. DO NOT EDIT.
// goctl 2.0.0

package types

import "github.com/1084217636/linkgo-im/api"

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token         string              `json:"token"`
	UserID        string              `json:"user_id"`
	Conversations []*api.Conversation `json:"conversations"`
}

type HistoryReq struct {
	TargetID string `form:"target_id"`
}

// Type manually customised to reference proto api.WireMessage.
type HistoryResp struct {
	Data []*api.WireMessage `json:"data"`
}

type GroupCreateReq struct {
	GroupID string   `json:"group_id"`
	Name    string   `json:"name"`
	Members []string `json:"members"`
}

type GroupCreateResp struct {
	GroupID string `json:"group_id"`
	Members int    `json:"members"`
	Msg     string `json:"msg"`
}

type UserGroupsResp struct {
	Groups []string `json:"groups"`
}

type FriendApplyReq struct {
	TargetUserID string `json:"target_user_id"`
	Message      string `json:"message"`
}

type FriendApplyResp struct {
	FromUserID string `json:"from_user_id"`
	ToUserID   string `json:"to_user_id"`
	Status     string `json:"status"`
	UpdatedAt  int64  `json:"updated_at"`
}

type FriendRespondReq struct {
	FromUserID string `json:"from_user_id"`
	Action     string `json:"action"`
}

type FriendRespondResp struct {
	FromUserID string `json:"from_user_id"`
	ToUserID   string `json:"to_user_id"`
	Status     string `json:"status"`
	UpdatedAt  int64  `json:"updated_at"`
}

type FriendInfo struct {
	UserID    string `json:"user_id"`
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
}

type FriendListResp struct {
	Friends []FriendInfo `json:"friends"`
}

type FriendRequestInfo struct {
	FromUserID string `json:"from_user_id"`
	ToUserID   string `json:"to_user_id"`
	Message    string `json:"message"`
	Status     string `json:"status"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type FriendRequestsResp struct {
	Requests []FriendRequestInfo `json:"requests"`
}

type GroupMemberInfo struct {
	UserID    string `json:"user_id"`
	Role      string `json:"role"`
	Status    string `json:"status"`
	MuteUntil int64  `json:"mute_until"`
	JoinedAt  int64  `json:"joined_at"`
}

type GroupMembersReq struct {
	GroupID string `form:"group_id"`
}

type GroupMembersResp struct {
	GroupID string            `json:"group_id"`
	Members []GroupMemberInfo `json:"members"`
}

type RedPacketCreateReq struct {
	TargetID       string `json:"target_id"`
	ToType         string `json:"to_type,optional"`
	ConversationID string `json:"conversation_id,optional"`
	TotalAmount    int64  `json:"total_amount"`
	TotalCount     int    `json:"total_count"`
	Greeting       string `json:"greeting,optional"`
	ExpiresAt      int64  `json:"expires_at,optional"`
}

type RedPacketInfo struct {
	RedPacketID     string `json:"red_packet_id"`
	SenderID        string `json:"sender_id"`
	ConversationID  string `json:"conversation_id"`
	ToType          string `json:"to_type"`
	TotalAmount     int64  `json:"total_amount"`
	TotalCount      int    `json:"total_count"`
	RemainingAmount int64  `json:"remaining_amount"`
	RemainingCount  int    `json:"remaining_count"`
	Greeting        string `json:"greeting"`
	Status          string `json:"status"`
	CreatedAt       int64  `json:"created_at"`
	ExpiresAt       int64  `json:"expires_at"`
	UpdatedAt       int64  `json:"updated_at"`
}

type RedPacketCreateResp struct {
	Packet RedPacketInfo `json:"packet"`
}

type RedPacketClaimReq struct {
	RedPacketID string `json:"red_packet_id"`
}

type RedPacketClaimResp struct {
	RedPacketID    string `json:"red_packet_id"`
	UserID         string `json:"user_id"`
	Amount         int64  `json:"amount"`
	CreatedAt      int64  `json:"created_at"`
	AlreadyClaimed bool   `json:"already_claimed"`
	Status         string `json:"status"`
}

type RedPacketDetailReq struct {
	RedPacketID string `form:"red_packet_id"`
}

type RedPacketClaimInfo struct {
	RedPacketID string `json:"red_packet_id"`
	UserID      string `json:"user_id"`
	Amount      int64  `json:"amount"`
	CreatedAt   int64  `json:"created_at"`
}

type RedPacketDetailResp struct {
	Packet  RedPacketInfo        `json:"packet"`
	Claims  []RedPacketClaimInfo `json:"claims"`
	Claimed bool                 `json:"claimed"`
}
