apiVersion: v1
kind: ConfigMap
metadata:
  name: linkgo-im-config
  namespace: linkgo-im
data:
  REDIS_ADDR: redis.default.svc.cluster.local:6379
  ETCD_ENDPOINTS: etcd.default.svc.cluster.local:2379
  DB_DSN: root:root@tcp(mysql.default.svc.cluster.local:3306)/linkgo_im?charset=utf8mb4&parseTime=True&loc=Local
  KAFKA_BROKERS: kafka.default.svc.cluster.local:9092
  KAFKA_GROUP_TOPIC: group_message_dispatch
  KAFKA_RETRY_TOPIC: group_message_retry
  KAFKA_DLQ_TOPIC: group_message_dlq
  KAFKA_CONSUMER_GROUP: transfer-group
  ROUTE_TTL_SECONDS: "75"
  TRANSFER_METRICS_PORT: "9102"
