apiVersion: v1
kind: Secret
metadata:
  name: linkgo-im-secret
  namespace: linkgo-im
type: Opaque
stringData:
  REDIS_PASSWORD: "123456"
  JWT_SECRET: "linkgo_im_secret_2026"
  MYSQL_ROOT_PASSWORD: "root"
  DB_DSN: "root:root@tcp(mysql.linkgo-im.svc.cluster.local:3306)/linkgo_im?charset=utf8mb4&parseTime=True&loc=Local"
