apiVersion: v1
kind: Secret
metadata:
  name: linkgo-im-secret
  namespace: linkgo-im
type: Opaque
stringData:
  REDIS_PASSWORD: "123456"
  JWT_SECRET: "linkgo_im_secret_2026"
  MYSQL_ROOT_PASSWORD: "root"
