// Code generated by goctl. DO NOT EDIT.
// goctl 2.0.0

package handler

import (
	"context"
	"net/http"

	gwmiddleware "github.com/1084217636/linkgo-im/cmd/gateway/internal/middleware"
	"github.com/1084217636/linkgo-im/cmd/gateway/internal/svc"
	"github.com/1084217636/linkgo-im/internal/health"
	"github.com/1084217636/linkgo-im/internal/metrics"
	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	// Infrastructure endpoints (not in .api file).
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: health.LiveHandler(),
			},
			{
				Method: http.MethodGet,
				Path:   "/readyz",
				Handler: health.ReadyHandler(map[string]health.Check{
					"redis": func(ctx context.Context) error {
						return serverCtx.Rdb.Ping(ctx).Err()
					},
					"mysql": func(ctx context.Context) error {
						if serverCtx.DB == nil {
							return nil
						}
						return serverCtx.DB.PingContext(ctx)
					},
				}),
			},
			{
				Method:  http.MethodGet,
				Path:    "/metrics",
				Handler: metrics.Handler().ServeHTTP,
			},
		},
	)

	// Public endpoints (JWT is optional — only rate limit applies).
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{
				gwmiddleware.NewRateLimitMiddleware(serverCtx.RestLimiter).Handle,
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
		),
		rest.WithPrefix("/api/v1"),
	)

	// Authenticated endpoints.
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{
				gwmiddleware.NewAuthMiddleware().Handle,
				gwmiddleware.NewRateLimitMiddleware(serverCtx.RestLimiter).Handle,
			},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/history",
				Handler: HistoryHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/friend/apply",
				Handler: FriendApplyHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/friend/respond",
				Handler: FriendRespondHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/friends",
				Handler: FriendListHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/friend/requests",
				Handler: FriendRequestsHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/group/create",
				Handler: GroupCreateHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/group/members",
				Handler: GroupMembersHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/user/groups",
				Handler: UserGroupsHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/red-packets",
				Handler: RedPacketCreateHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/red-packets/claim",
				Handler: RedPacketClaimHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/red-packets/detail",
				Handler: RedPacketDetailHandler(serverCtx),
			},
		),
		rest.WithPrefix("/api/v1"),
	)

	// WebSocket endpoint (not in .api file — uses different rate limiter).
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{
				gwmiddleware.NewAuthMiddleware().Handle,
				gwmiddleware.NewRateLimitMiddleware(serverCtx.WsLimiter).Handle,
			},
			rest.Route{
				Method:  http.MethodGet,
				Path:    "/ws",
				Handler: WebSocketHandler(serverCtx),
			},
		),
	)
}
