// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserId string `json:"user_id"`
	Token  string `json:"token"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Mobile   string `json:"mobile"`
}

type RegisterResp struct {
	UserId string `json:"user_id"`
	Token  string `json:"token"`
}
