// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/protocol.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义消息类型枚举
type MsgType int32

const (
	MsgType_NORMAL    MsgType = 0 // 普通消息
	MsgType_HEARTBEAT MsgType = 1 // 心跳包
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "NORMAL",
		1: "HEARTBEAT",
	}
	MsgType_value = map[string]int32{
		"NORMAL":    0,
		"HEARTBEAT": 1,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protocol_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_api_protocol_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{0}
}

// --- Logic 服务接口 ---
type PushMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 谁发的
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`             // 原始内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsgReq) Reset() {
	*x = PushMsgReq{}
	mi := &file_api_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgReq) ProtoMessage() {}

func (x *PushMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgReq.ProtoReflect.Descriptor instead.
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *PushMsgReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PushMsgReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type PushMsgReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsgReply) Reset() {
	*x = PushMsgReply{}
	mi := &file_api_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgReply) ProtoMessage() {}

func (x *PushMsgReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgReply.ProtoReflect.Descriptor instead.
func (*PushMsgReply) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{1}
}

type UserLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginReq) Reset() {
	*x = UserLoginReq{}
	mi := &file_api_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginReq) ProtoMessage() {}

func (x *UserLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginReq.ProtoReflect.Descriptor instead.
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserLoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginReply) Reset() {
	*x = UserLoginReply{}
	mi := &file_api_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginReply) ProtoMessage() {}

func (x *UserLoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginReply.ProtoReflect.Descriptor instead.
func (*UserLoginReply) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{3}
}

// 【新增】获取历史消息请求
type GetHistoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 当前用户ID
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 目标ID（用户ID或群ID）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryReq) Reset() {
	*x = GetHistoryReq{}
	mi := &file_api_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryReq) ProtoMessage() {}

func (x *GetHistoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryReq.ProtoReflect.Descriptor instead.
func (*GetHistoryReq) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *GetHistoryReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetHistoryReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

// 【新增】获取历史消息响应
type GetHistoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []string               `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"` // 返回的消息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryReply) Reset() {
	*x = GetHistoryReply{}
	mi := &file_api_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryReply) ProtoMessage() {}

func (x *GetHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryReply.ProtoReflect.Descriptor instead.
func (*GetHistoryReply) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *GetHistoryReply) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

// 增加这两个结构
type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_api_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_api_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// --- Gateway 服务接口 ---
type SendToUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  string                 `protobuf:"bytes,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToUserReq) Reset() {
	*x = SendToUserReq{}
	mi := &file_api_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUserReq) ProtoMessage() {}

func (x *SendToUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUserReq.ProtoReflect.Descriptor instead.
func (*SendToUserReq) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *SendToUserReq) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *SendToUserReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type SendToUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendToUserReply) Reset() {
	*x = SendToUserReply{}
	mi := &file_api_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendToUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendToUserReply) ProtoMessage() {}

func (x *SendToUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendToUserReply.ProtoReflect.Descriptor instead.
func (*SendToUserReply) Descriptor() ([]byte, []int) {
	return file_api_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *SendToUserReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_protocol_proto protoreflect.FileDescriptor

const file_api_protocol_proto_rawDesc = "" +
	"\n" +
	"\x12api/protocol.proto\x12\x03api\"?\n" +
	"\n" +
	"PushMsgReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\x0e\n" +
	"\fPushMsgReply\"'\n" +
	"\fUserLoginReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x10\n" +
	"\x0eUserLoginReply\"E\n" +
	"\rGetHistoryReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\"-\n" +
	"\x0fGetHistoryReply\x12\x1a\n" +
	"\bmessages\x18\x01 \x03(\tR\bmessages\"B\n" +
	"\bLoginReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\";\n" +
	"\n" +
	"LoginReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"O\n" +
	"\rSendToUserReq\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\tR\ftargetUserId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"+\n" +
	"\x0fSendToUserReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*$\n" +
	"\aMsgType\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\r\n" +
	"\tHEARTBEAT\x10\x012\xd0\x01\n" +
	"\x05Logic\x12'\n" +
	"\x05Login\x12\r.api.LoginReq\x1a\x0f.api.LoginReply\x121\n" +
	"\vPushMessage\x12\x0f.api.PushMsgReq\x1a\x11.api.PushMsgReply\x123\n" +
	"\tUserLogin\x12\x11.api.UserLoginReq\x1a\x13.api.UserLoginReply\x126\n" +
	"\n" +
	"GetHistory\x12\x12.api.GetHistoryReq\x1a\x14.api.GetHistoryReply2A\n" +
	"\aGateway\x126\n" +
	"\n" +
	"PushToUser\x12\x12.api.SendToUserReq\x1a\x14.api.SendToUserReplyB\aZ\x05./apib\x06proto3"

var (
	file_api_protocol_proto_rawDescOnce sync.Once
	file_api_protocol_proto_rawDescData []byte
)

func file_api_protocol_proto_rawDescGZIP() []byte {
	file_api_protocol_proto_rawDescOnce.Do(func() {
		file_api_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protocol_proto_rawDesc), len(file_api_protocol_proto_rawDesc)))
	})
	return file_api_protocol_proto_rawDescData
}

var file_api_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_protocol_proto_goTypes = []any{
	(MsgType)(0),            // 0: api.MsgType
	(*PushMsgReq)(nil),      // 1: api.PushMsgReq
	(*PushMsgReply)(nil),    // 2: api.PushMsgReply
	(*UserLoginReq)(nil),    // 3: api.UserLoginReq
	(*UserLoginReply)(nil),  // 4: api.UserLoginReply
	(*GetHistoryReq)(nil),   // 5: api.GetHistoryReq
	(*GetHistoryReply)(nil), // 6: api.GetHistoryReply
	(*LoginReq)(nil),        // 7: api.LoginReq
	(*LoginReply)(nil),      // 8: api.LoginReply
	(*SendToUserReq)(nil),   // 9: api.SendToUserReq
	(*SendToUserReply)(nil), // 10: api.SendToUserReply
}
var file_api_protocol_proto_depIdxs = []int32{
	7,  // 0: api.Logic.Login:input_type -> api.LoginReq
	1,  // 1: api.Logic.PushMessage:input_type -> api.PushMsgReq
	3,  // 2: api.Logic.UserLogin:input_type -> api.UserLoginReq
	5,  // 3: api.Logic.GetHistory:input_type -> api.GetHistoryReq
	9,  // 4: api.Gateway.PushToUser:input_type -> api.SendToUserReq
	8,  // 5: api.Logic.Login:output_type -> api.LoginReply
	2,  // 6: api.Logic.PushMessage:output_type -> api.PushMsgReply
	4,  // 7: api.Logic.UserLogin:output_type -> api.UserLoginReply
	6,  // 8: api.Logic.GetHistory:output_type -> api.GetHistoryReply
	10, // 9: api.Gateway.PushToUser:output_type -> api.SendToUserReply
	5,  // [5:10] is the sub-list for method output_type
	0,  // [0:5] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_protocol_proto_init() }
func file_api_protocol_proto_init() {
	if File_api_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protocol_proto_rawDesc), len(file_api_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_protocol_proto_goTypes,
		DependencyIndexes: file_api_protocol_proto_depIdxs,
		EnumInfos:         file_api_protocol_proto_enumTypes,
		MessageInfos:      file_api_protocol_proto_msgTypes,
	}.Build()
	File_api_protocol_proto = out.File
	file_api_protocol_proto_goTypes = nil
	file_api_protocol_proto_depIdxs = nil
}
